[tool.poetry]
name = "dj-stripe"
version = "2.7.0-beta.1"
description = "Django + Stripe made easy"
license = "MIT"
authors = [
    "Alexander Kavanaugh <alex@kavdev.io>",
    "Jerome Leclanche <jerome@leclan.ch>",
]
readme = "docs/README.md"
homepage = "https://dj-stripe.dev"
repository = "https://github.com/dj-stripe/dj-stripe"
documentation = "https://dj-stripe.github.io/dj-stripe/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Topic :: Office/Business :: Financial",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
]

packages = [
    { include = "djstripe" }
]
include = [
    "AUTHORS.md",
    "CONTRIBUTING.md",
    "HISTORY.md",
    "LICENSE",
]
exclude = [
    "manage.py"
]

[tool.poetry.urls]
"Funding" = "https://github.com/sponsors/dj-stripe"


[tool.poetry.dependencies]
python = "^3.7.12"
django = ">=3.2, <4.1"
jsonfield = ">=3.0"
stripe = ">=2.48.0"
psycopg2 = { version = "^2.8.5", optional = true }
mysqlclient = { version = ">=1.4.0", optional = true }

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pytest = "^7.1.2"
pytest-django = "^4.5.2"
mypy = "^0.971"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.3.1"
mkdocstrings = "^0.19.0"
mkdocs-material = "^8.4.2"
mkdocs-autorefs = "^0.4.1"
mike = "^1.1.2"
jinja2 = "<3.1.0"


[tool.poetry.extras]
docs = ["mkdocs", "mkdocstrings", "mkdocs-material", "mkdocs-autorefs", "mike", "jinja2"]
postgres = ["psycopg2"]
mysql = ["mysqlclient"]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
