name: Build and deploy docs

on:
  push:
    branches:
      - "master"
      # Push events to branches matching
      # refs/heads/stable/2.5
      # refs/heads/stable/10
      # refs/heads/stable/2
      # refs/heads/stable/2.5.6
      - "stable/[0-9]+(.[0-9])*(.[0-9])*"

  workflow_dispatch: # to trigger manually

env:
  POETRY_VERSION: "1.2.2"
  POETRY_VIRTUALENVS_IN_PROJECT: "1"
  LATEST_STABLE_BRANCH: "stable/2.7"
  GIT_COMMITTER_NAME: "dj-stripe commit bot"
  GIT_COMMITTER_EMAIL: "admin@djstripe.dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry (${{ env.POETRY_VERSION }}) binary on runner
        run: |
          curl -sL https://install.python-poetry.org | python - --version ${{ env.POETRY_VERSION }}

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: timeout 10s poetry run pip --version || rm -rf .venv

      - name: Install dependencies
        run: poetry install --with docs

      - name: Fetch gh-pages remote changes (if any)
        run: git fetch origin gh-pages --depth=1

      - name: Deploy (and Update) docs for the branch
        run: poetry run mike deploy --push --rebase "${GITHUB_REF##*/}"

      - name: Set default docs version
        run: poetry run mike set-default --push --rebase "${LATEST_STABLE_BRANCH##*/}"
